module.exports = [{
		imgAnime: "https://kaysil.dev/hy-tomboy.png",
		colorBg: "#45f248"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Ue9JgZFiDa0/YTDEDdvksAI/AAAAAAAAw7A/7NK_0YhtWHY799sYCFcY0hLXbHkB-KpjQCNcBGAsYHQ/s120/yato.png",
		colorBg: "#505061"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ttJapMwcp0Y/YTDDQeQ8J-I/AAAAAAAAw64/a4HG6G-N7u0fkSyewCRZdwu2gXAQvv-5QCNcBGAsYHQ/s120/yuu-otosaka.png",
		colorBg: "#87635f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-plAW9pJE7kI/YS9_tSaSSUI/AAAAAAAAw5Q/rBQfyflYa4Ya8EZ3q4d5gnTPvssBRvINwCNcBGAsYHQ/s120/mizuhara-chizuru.png",
		colorBg: "#ec8aa1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-RTZ_8x1kYXE/YS-AMYCLT3I/AAAAAAAAw5Y/cnWceiPiQBES7naVwkIjlQG0hksM4bwkgCNcBGAsYHQ/s120/nanami-mami.png",
		colorBg: "#e9cf75"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-iWYzgznYZqs/YS-A-eFMChI/AAAAAAAAw5g/fUSVNmVZjiMeeAfhr6-TEt7QUB8oQ_aewCNcBGAsYHQ/s120/sarashina-ruka.png",
		colorBg: "#72a6ca"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-QCD0kGdPosc/YS-BnMFyFII/AAAAAAAAw5o/7vvomvfqgCsKqNYmN2CHtGQm83aSEW5ZQCNcBGAsYHQ/s120/sakurasawa-sumi.png",
		colorBg: "#eb95ab"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-9x-5Z7CEsag/YRd9DWpiJ-I/AAAAAAAAwRY/DNlMLG12fPAmeeZKLXMcy_O6jb7XT_-nACNcBGAsYHQ/s120/kaneki-ken.png",
		colorBg: "#b22a2a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-9WD9n1tXeSE/YS99QxqIITI/AAAAAAAAw44/0c2LNr0d5Mon0RqhLrLCueo47CPNDdMdACNcBGAsYHQ/s120/juuzou.png",
		colorBg: "#c43432"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-uCAwvdz8eNQ/YS82B8WTHWI/AAAAAAAAw3o/U9-pyn0DGkMFFJ-2GODNLF6ZJPH1_P7wgCNcBGAsYHQ/s120/yamauchi-sakura.png",
		colorBg: "#64608a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-QySgGHQhIoI/YROZ-v4_rlI/AAAAAAAAwGU/jRJEmaRhtDMh9SgFeq27R0dL6BJyXUA5ACNcBGAsYHQ/s120/rem.png",
		colorBg: "#64608a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--DiPxjdwnEE/YS81XhnQJfI/AAAAAAAAw3g/GRCKPTOL8qoRSbuxXl2jTPZeLbMv5q9OwCNcBGAsYHQ/s120/emilia.png",
		colorBg: "#a372c2"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ik-NMUqZN5E/YTDBxYkkiUI/AAAAAAAAw6w/siHXmOdbIsQVhCffF1YJV3bC1WQzLQ9DgCNcBGAsYHQ/s120/raiden-mei-herrscher.png",
		colorBg: "#d22a3c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-4tv2czpE4Vk/YS80Vh42nOI/AAAAAAAAw3Y/yRmuTPlHnG0NOh5gHWHHPziKGYyvUpHYgCNcBGAsYHQ/s120/raiden-mei.png",
		colorBg: "#5c74ce"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-q6amnLdL5gc/YSy2VFQmhXI/AAAAAAAAw2E/ExCR7ggPpsAaWSVbEbnxqDR8_34NFBt9wCNcBGAsYHQ/s120/koro-sensei.png",
		colorBg: "#ffca4e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-UtholY3Us_8/YSy1KRNnLmI/AAAAAAAAw18/lMGQRiVbXrsOiJzZszNJCwsYiwrjwiB0QCNcBGAsYHQ/s120/runa.png",
		colorBg: "#ee8c6f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-2iBSFx4nMNI/YSys1xzxl8I/AAAAAAAAw1s/_Th7BUaRnnEmD1AgDLD7wVZ22E0fvLSxgCNcBGAsYHQ/s120/gintoki.png",
		colorBg: "#6984b7"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-NgD81tLgq84/YSyrizMSJEI/AAAAAAAAw1c/lNH0mV-av2EfvNOG_-DxdJiGCDeRDM7rwCNcBGAsYHQ/s120/raphtalia.png",
		colorBg: "#d58390"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-iCpLylmNJf4/YSyq5Gj06iI/AAAAAAAAw1U/2iRtPrlXKJ4ywgQBKC7rju10YSx29wdbQCNcBGAsYHQ/s120/sukuna.png",
		colorBg: "#c66163"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-IF9ZetPgBCY/YSo3XDvvUvI/AAAAAAAAwzA/0y9SNdrheFUVh78YDcaqR3WS1EWxDm7eACNcBGAsYHQ/s120/nanami.png",
		colorBg: "#5997a5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-3N8lN_gj3BM/YSo2wYR67eI/AAAAAAAAwy4/KSjXnRZmytgBWkmFyq_kWCaJQaAZp2xXQCNcBGAsYHQ/s120/ai-ohto.png",
		colorBg: "#498ce0"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CfaXVswhFlc/YSo0_ftKbAI/AAAAAAAAwyg/m2ARw0bvWPsZxBQs1vZfpiJQN_Ozk__3wCNcBGAsYHQ/s120/mona.png",
		colorBg: "#7d58de"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-MhWeQZgDeGM/YSoz6-Yz1ZI/AAAAAAAAwyY/DU6rO-GCSWAiGsg6R7GqKiGZKQ1TlvRfgCNcBGAsYHQ/s120/lisa.png",
		colorBg: "#86679a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-MpM8vuBW4Fo/YSozXoRRFAI/AAAAAAAAwyQ/Y3BHq5j4ydMEuTAz_if12ugcagnppIbMACNcBGAsYHQ/s120/keqing.png",
		colorBg: "#6a4e90"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-VtRHcjXGE-I/YSowpsaQU9I/AAAAAAAAwyI/cOF78vqrev4ZP3czG9s4WI-6_vdfQ30hgCNcBGAsYHQ/s120/fischl.png",
		colorBg: "#59a1c9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CWPuDY1sHy8/YSov6KDnnsI/AAAAAAAAwyA/oONr2f3b7EA3qp-ouuPYl9iCmvSFUMDQACNcBGAsYHQ/s120/jean.png",
		colorBg: "#8669aa"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xPIn5BVtsJo/YSovHVFrcNI/AAAAAAAAwx4/w7qKslSrWCsrc5wE12BuIVarAiBOpIypgCNcBGAsYHQ/s120/ganyu.png",
		colorBg: "#5f8bb6"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-aD3BWx3PX4o/YSSzzwhT81I/AAAAAAAAwoM/MC9BwyJ7JJUgWRS2Ltxj7sWzcs26XDlxgCNcBGAsYHQ/s120/raiden-shogun.png",
		colorBg: "#795dd1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-jpzot7a6g2Y/YSIbEDq8MwI/AAAAAAAAwjQ/0nfGzDI8_-w1cXTZ1Yhn7rHQPHXUzXkDACNcBGAsYHQ/s120/qiqi-trinh.png",
		colorBg: "#8681ac"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-R8PRV2YKFaY/YSIXLIHI8FI/AAAAAAAAwi4/Yz6WOatmQD0tEAKSo1fslMzXPSPZbKJ9gCNcBGAsYHQ/s120/ayaka.png",
		colorBg: "#829fbc"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-d3zb2yEzwc0/YSYzeBRcRfI/AAAAAAAAwqc/yLDHOVsFGwg4XNN4d0eeUVdchKqukX-swCNcBGAsYHQ/s120/killua-zoldyck.png",
		colorBg: "#596890"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-VrjL5ENpGOA/YSYygPaJ8OI/AAAAAAAAwqU/wV_PIJdICOkS2rRNUhIEDsRtU7FtVHDpwCNcBGAsYHQ/s120/hanako.png",
		colorBg: "#845c5c"
	},
	{
		imgAnime: "https://1.bp.blogspot.com/-PyYvjL4q_pU/YSYyB9jk92I/AAAAAAAAwqM/mjr1Wg-K3gotm7IbF7ydABGSsSMTSfzAQCNcBGAsYHQ/s120/saber.png",
		colorBg: "#5a9ece"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-jXl6-T3ZDqU/YSIdY5NKglI/AAAAAAAAwjY/BwD8wWrB_Fk0_WfW8hNXOEFruLsULSImACNcBGAsYHQ/s120/sakura-saber.png",
		colorBg: "#6ab9be"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-awOrSY3Dk20/YSSuDFBK2ZI/AAAAAAAAwns/Q-HkhLVGuNATAKxOt6HYb2r5-HW5Gjf8ACNcBGAsYHQ/s120/sato-kazuma.png",
		colorBg: "#5e9794"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-4rKk4RKASrQ/YSSupvK-BII/AAAAAAAAwn0/nOhYCRVpX38TzyyhKSogbL8e6BPSPc3ZQCNcBGAsYHQ/s120/aqua.png",
		colorBg: "#67a3df"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-vOdrOLFkekI/YSSvrOuDwrI/AAAAAAAAwn8/a1izC4mSmdsI5hw1Dh3bAQJCq3Xgw5E5gCNcBGAsYHQ/s120/megumin.png",
		colorBg: "#d75151"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZfOVb2CYh-s/YSSwqu8UA5I/AAAAAAAAwoE/KMOgEPK_afQXg1szgM9XFNCF6sFoZretgCNcBGAsYHQ/s120/darkness.png",
		colorBg: "#f1c16c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-d_iAO0LUAkU/YSStM_SyPBI/AAAAAAAAwnk/IC6OnZHTWMArDcN7-8abWrCuY8OwOCubgCNcBGAsYHQ/s120/kyaru.png",
		colorBg: "#9888ae"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-nTgmjI5le5s/YRYfMrVob-I/AAAAAAAAwOA/JlyK9C3ckdcVs957y8L8fEjuCaxfHv9bgCNcBGAsYHQ/s120/miku.png",
		colorBg: "#70adb7"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-PyyVxE1fOdk/YSOYsZpnlbI/AAAAAAAAwmk/Pie_6sCIamQ07_vVQIIbTvfh8W0NYBEKwCNcBGAsYHQ/s120/shido.png",
		colorBg: "#4d5190"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-3LHa3SDsYa4/YRM6c2x61fI/AAAAAAAAwFo/-FRHA-xDPloZORv9DkwmI0kRjMzC_agPQCNcBGAsYHQ/s120/kurumi.png",
		colorBg: "#4d5190"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-YXmjYIR-yGA/YSOYCV-tiLI/AAAAAAAAwmc/Hbf1fHEUZ8UTg9einGTcUsZZ7bZrwRghACNcBGAsYHQ/s120/kaguya.png",
		colorBg: "#cf332b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-s0VbdUnhjUA/YSOXkxqAJII/AAAAAAAAwmU/hSKwGzCiqAYXxsLfAf01m9sV-CdHSOqigCNcBGAsYHQ/s120/ainz-ooal-gown.png",
		colorBg: "#9463bf"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-vt5-jzGiOH8/YSOWo5xH6JI/AAAAAAAAwmM/0D9lOvuInp4QEowOZmTPw8JkzJ87RFqxACNcBGAsYHQ/s120/milim.png",
		colorBg: "#dcaaa4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-D_8PxJ58tYE/YQqczcsSdoI/AAAAAAAAv3U/M9Z4JB8BYD4IN54qgld45M1G2l9NKD54ACNcBGAsYHQ/s120/tanjiro.png",
		colorBg: "#3b9172"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-1lzQ9TBEEtA/YQqczRz91DI/AAAAAAAAv3Y/xSE5cIapEx81y-drb8pTFBX5sXytr-DZACNcBGAsYHQ/s120/nezuko.png",
		colorBg: "#d19397"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-rMFuWp2MFiA/YRYgnPhwtyI/AAAAAAAAwOQ/r2cGi9q0x5YtevOyRHpRW4nnoMwGI0MZQCNcBGAsYHQ/s120/zenitsu.png",
		colorBg: "#fabd4b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-DZnM8Bi1E5U/YRYieXtGPkI/AAAAAAAAwOg/Uf5Z5I8B1OkfiRf-WsPtmvhhPI2FjpIlwCNcBGAsYHQ/s120/inosuke.png",
		colorBg: "#a58266"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-py52JcBDjg0/YSOT7TUQ7pI/AAAAAAAAwl0/PfKoiNsEaLohOE0Mk1ygke6FQCZd2OQhQCNcBGAsYHQ/s120/yoriichi.png",
		colorBg: "#b83b2e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-VnYeh96cxLY/YSOS_DRgI2I/AAAAAAAAwls/X7FgEYMgjkI_N-1WU1Rb-1I-1R4AicdhwCNcBGAsYHQ/s120/kokushibou.png",
		colorBg: "#9c2e32"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZTW2Ytci2gc/YQkMQ0IycxI/AAAAAAAAv1I/QDnmL3LLZxQ3uj0UpIokrXYX8uwJRgJBgCNcBGAsYHQ/s120/giyuu.png",
		colorBg: "#223657"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-mSeoBZHv-cw/YQkM6De4UUI/AAAAAAAAv1Q/MEr020DjhR8Ob0ioe2vPflEGqtYtpjYPQCNcBGAsYHQ/s120/shinobu.png",
		colorBg: "#ae9dd9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-0kFlQv2Y08Q/YRCIBB6CvxI/AAAAAAAAwCk/Nv77gqkCpScc3f9lXVKPnZu6aCRebUhNQCNcBGAsYHQ/s120/muichirou.png",
		colorBg: "#2c8889"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-DqRWFEqlCwM/YS99-o8ickI/AAAAAAAAw5A/25CkdoaSPDA_TR_BUEjsMYQ7RwavDOOdgCNcBGAsYHQ/s120/sabito.png",
		colorBg: "#9b9cc5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-UTKm-6dLGfg/YS9-oyey5cI/AAAAAAAAw5I/t-_pn2SQ5lU2_0_7YjVtGpr5VM0Id0LrACNcBGAsYHQ/s120/makomo.png",
		colorBg: "#ec8aa1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-qlBDcB0z1Mo/YROe9ophi1I/AAAAAAAAwGk/lY-9KYqFghQFiBlekRn-kfZFzZWN0K8vgCNcBGAsYHQ/s120/rengoku.png",
		colorBg: "#db4032"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xuj_Dk_DwIo/YSzu0bEAk6I/AAAAAAAAw2M/Rpbv5dbTHm4ru3ngvXXfUj9KBxR-Yw2DQCNcBGAsYHQ/s120/akaza.png",
		colorBg: "#df94a7"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-LJRRo4gBs7Q/YRO2VozYvyI/AAAAAAAAwGs/L-KaVFidh5IJd6JhRQgOCQ1yWlJPWl3bQCNcBGAsYHQ/s120/takemichi.png",
		colorBg: "#3ea8c6"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-uRWT9cFz-YM/YRO2V63jXNI/AAAAAAAAwGw/SFnxNJ_o70c9MKAL-oPXcgCz38vrMwiLACNcBGAsYHQ/s120/hina.png",
		colorBg: "#ef93a2"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-eTuwjUKUhV0/YREhK8NVWmI/AAAAAAAAwEY/y53UXtV0nMU0eaevDg9Jby1gm1yQE0m-gCNcBGAsYHQ/s120/mikey.png",
		colorBg: "#2e2a28"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-KVp19_Hml0Y/YSo18XzX4VI/AAAAAAAAwyw/BBYZOdscXSoRXWbD989AzFpUPuaXIeRXQCNcBGAsYHQ/s120/emma.png",
		colorBg: "#d6ba62"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-rOMaglwetqw/YREhKg_tsVI/AAAAAAAAwEU/Qj5XpOlUk1IeHoOHWw8JUwn2afR1qPZIACNcBGAsYHQ/s120/draken.png",
		colorBg: "#1f242a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-4jbj8k0oAcM/YRSr5HqBM5I/AAAAAAAAwJQ/Swt100rUtk06KL8TWCcIZ92s8lTNpZ9xgCNcBGAsYHQ/s120/kisaki.png",
		colorBg: "#caab2f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-QqE2bIkcOZ4/YRFCN1Pws4I/AAAAAAAAwEk/xFgTOqAw9_EMwwO86Mb3zO0m7BPlrNfhQCNcBGAsYHQ/s120/chifuyu.png",
		colorBg: "#243231"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-lSPUp5eyKnM/YRSHaw7DhTI/AAAAAAAAwJE/B8P5Hkzg_OwsU2DF27uhnT3gfNrP1SQ2wCNcBGAsYHQ/s120/mitsuya.png",
		colorBg: "#51597d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6ZoqKHAqDHQ/YRY20hJoUwI/AAAAAAAAwPU/H0ubM8HXIv4RfYfttJPK_16ZKc2uGWLGACNcBGAsYHQ/s120/baji.png",
		colorBg: "#6b625b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-g9cX0xoMw0w/YReDa7UKVVI/AAAAAAAAwRg/P3wp1Jmrox8Awe-iWZoJzxuqrNq-yr4eQCNcBGAsYHQ/s120/haitani-ran.png",
		colorBg: "#d1ae59"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-As2l6-o5qwE/YReKZTUrISI/AAAAAAAAwR4/8zeY6TjRL8QFMMOKbcSDZMLO_wtqh1F0QCNcBGAsYHQ/s120/haitani-rindou.png",
		colorBg: "#988cb3"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6ofCjMnNozU/YReFvskmATI/AAAAAAAAwRo/J1_hfHGVa4E_e1Wq1tNZx8OaSk7iXjsTACNcBGAsYHQ/s120/kawaragi-senju.png",
		colorBg: "#9099be"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CSUXv_6Mzyk/YReHh4rwvFI/AAAAAAAAwRw/YTY2ZPSXRHYFmL93Q1vvnAdk2rYqx_3KQCNcBGAsYHQ/s120/izana-kurokawa.png",
		colorBg: "#746db6"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-pQ0-vSzmK9I/YSOV-Abl-PI/AAAAAAAAwmE/-lFZ7zCBgt0gQIpaFepjW0DqtRAYO1x2QCNcBGAsYHQ/s120/kazutora.png",
		colorBg: "#d7ba61"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZYSwi6ydyko/YTDA3Vs_d2I/AAAAAAAAw6o/HRq4bpRZPRMhko7QP3wdY6fAeqE2EJL9gCNcBGAsYHQ/s120/hanma.png",
		colorBg: "#7d957d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-nPonIkatt88/YRzIaPpi56I/AAAAAAAAwb0/5c5OMkWZ8UIaqteplu9IsgDK9AyT9w0qACNcBGAsYHQ/s120/imaushi.png",
		colorBg: "#d71e1e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-8qoNfyqkEO4/YSOSYaIsEMI/AAAAAAAAwlk/uTZCVrF6UjIZyQAEqmmFt4FPxoJkI3NFwCNcBGAsYHQ/s120/karma.png",
		colorBg: "#8a695c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-9yp-Meoqb3M/YRoljWoM3XI/AAAAAAAAwYU/kyqmIjGW2oMent2Bexu-X4HkAd2f9eTpACNcBGAsYHQ/s120/nagisa.png",
		colorBg: "#6e99c2"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-HniZtfzU0FU/YSORrle6wQI/AAAAAAAAwlc/GbvJ7jGH-gQAI0mIQ-w6iDovHyE-67i8wCNcBGAsYHQ/s120/kotori.png",
		colorBg: "#ed9595"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-OWoTcCKzihM/YSIak4FDQLI/AAAAAAAAwjI/_bfKY2D02IoNrz0eUMM2cF_oCZOT8K8OQCNcBGAsYHQ/s120/ruby-rose.png",
		colorBg: "#1f1c25"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-cajCPYtQJ8c/YSIXvi5nSMI/AAAAAAAAwjA/6J81Vc83G3wd8_JlOmRtnPqMXhsZ4CQBACNcBGAsYHQ/s120/gilgamesh.png",
		colorBg: "#829fbc"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Tn8X-VeRFDg/YSIWAH53gwI/AAAAAAAAwiw/IlI2FTaBpp4FUwdp4sFMX0RUEuST-AkvwCNcBGAsYHQ/s120/yugi.png",
		colorBg: "#47a0e5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-5nLOx_ngBhE/YSIVO-85gSI/AAAAAAAAwio/smiz82bnvxMZCyMCP7ihkaorU7FekzilACNcBGAsYHQ/s120/kaiba.png",
		colorBg: "#1987dc"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-F9rhPF9O8J4/YSIUQyTi76I/AAAAAAAAwig/QNLWOJHXkSA2D8uW0uujvnzPN1IgxlTyACNcBGAsYHQ/s120/rikka.png",
		colorBg: "#62bdc1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-OTOSiz2rU-4/YSITiEffGbI/AAAAAAAAwiY/Rb_HPPC3xQMe0XoXHAD7ghgMrF3GIvbrgCNcBGAsYHQ/s120/toge-inumaki.png",
		colorBg: "#5d6595"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-EpyBcYLhm1c/YSC9b3DD6xI/AAAAAAAAwiE/T9K2qkwu8FI8ZO6eYSjMQfxXybzY-znfwCNcBGAsYHQ/s120/megumi.png",
		colorBg: "#778aa4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-vhdXscLwLpA/YSC8vcHGfGI/AAAAAAAAwh8/vzuq8pP8LtA7htrWe-cmRlWgeZ-X20p7ACNcBGAsYHQ/s120/mahito.png",
		colorBg: "#7d919a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-yxfc3h7Z9v8/YR8tStp7s-I/AAAAAAAAwf0/3Xdh49pfIgsEu0CiJ5klDazeP6nPS0veQCNcBGAsYHQ/s120/xiao.png",
		colorBg: "#359e9b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-PqvcS2ihiFY/YR8pNRsxRqI/AAAAAAAAwe8/cBfsAJZW5C0lPTlChR151wQLPdCVDf6jgCNcBGAsYHQ/s120/nakano-ichika.png",
		colorBg: "#81b0d1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xBTn226-fsc/YR8pnsGniVI/AAAAAAAAwfE/g4c18MCOHiEc5k5c13wAFYbH19SbvpvUgCNcBGAsYHQ/s120/nakano-nino.png",
		colorBg: "#8d8ad5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-cE5wkzwUTYs/YR8qKOehEKI/AAAAAAAAwfM/ISqo2vslNGwub4toONQ3g23R2UxGRXwvACNcBGAsYHQ/s120/nakano-miku.png",
		colorBg: "#8d9ee0"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-udW1Hr18E9g/YR8qmi7gMeI/AAAAAAAAwfU/5GzcX-C1RzoMaBYh2-2gIT7xQaoPGr82ACNcBGAsYHQ/s120/nakano-yotsuba.png",
		colorBg: "#a1b369"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-EhXyCXjwzzQ/YR8q-yddHBI/AAAAAAAAwfc/Nwx8cfdXA5sK1tdTQnjVD65CCQuzY3ECQCNcBGAsYHQ/s120/nakano-itsuki.png",
		colorBg: "#d0797f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-iWpPbRc90DE/YR8nx58KiAI/AAAAAAAAwes/rayjadogDoA6NS0vHzCLmdJcKHRYJ8O6QCNcBGAsYHQ/s120/bakura-ryou.png",
		colorBg: "#7798ab"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-asAnOpdRjGY/YR8oW7OR46I/AAAAAAAAwe0/9r925vQ7QIkBSc8VOLPl_dH3YLmrUZgowCNcBGAsYHQ/s120/marik-ishtar.png",
		colorBg: "#75648c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-d0T3C-GEc_o/YR8l1cuS4VI/AAAAAAAAwec/5pwcxgbxNAEgkaM91kR7aC-AXP4bzyqkwCNcBGAsYHQ/s120/kiyotaka-ayanokōji.png",
		colorBg: "#ae3758"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-9o3VfXclCjI/YR0efaJrqWI/AAAAAAAAwcs/FUYhjAFOa5UcHQpVZHdBndXVe9oDdF4owCNcBGAsYHQ/s120/inuyasha.png",
		colorBg: "#b33232"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-_A3LKyDXLog/YRzCk8MJ_2I/AAAAAAAAwbk/3wVF7K__WTcdbSy8hV8EQuXtKpI4c1DCACNcBGAsYHQ/s120/sistine-fibel.png",
		colorBg: "#7066a4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-_t9XqCIJNsE/YRzErdOjFTI/AAAAAAAAwbs/b70p7XPMOC4C-_SNB9c7bCgi0G-WwfafgCNcBGAsYHQ/s120/syalis.png",
		colorBg: "#ae9bc9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-QA-T_TJQfwY/YRzCDJn8fAI/AAAAAAAAwbc/1QIBF53Cg2IVFpZDLOsb3WRmlecB-UhaACNcBGAsYHQ/s120/rei-ayanami.png",
		colorBg: "#8184c0"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-OZmIFmnVidg/YRpoBQGazSI/AAAAAAAAwZM/x6SgLYXa9TksSjMipERh0lxczqRYEHs9gCNcBGAsYHQ/s120/iruma.png",
		colorBg: "#3fafe8"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-o78BEas_k-I/YRpnXa1FW4I/AAAAAAAAwZE/yit4mL4lDjstn_qpo3LrulUdgc9c3ov6QCNcBGAsYHQ/s120/monika.png",
		colorBg: "#6b6cb3"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-vx2FmYGYDCw/YRpthu0wCqI/AAAAAAAAwZU/S4HRAYCtM4IdKP7qDsNRFxfajyx9UszNQCNcBGAsYHQ/s120/yuri.png",
		colorBg: "#967ea8"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-vM0G_d3lFEs/YRpm0ZKTPaI/AAAAAAAAwY8/yvxwYDQPKpMd3YK0A-pjPAs6XjhXUY4HACNcBGAsYHQ/s120/shigeo-kageyama.png",
		colorBg: "#56377a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-wJ-idSqrHqM/YRooLbjVYaI/AAAAAAAAwYs/Q1LS3_45gk84ELg9MPd_ZMiBjD3Nv-9HACNcBGAsYHQ/s120/elaina.png",
		colorBg: "#9e80af"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-We9e4i3lrco/YRonHbAFFyI/AAAAAAAAwYk/-qLa9GEhFRMLPg9wFnMuHB1Rylq7XwvXgCNcBGAsYHQ/s120/mirai.png",
		colorBg: "#e08e7c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-dVpmyiUWUjI/YRomRtXCTQI/AAAAAAAAwYc/KEo1d5_HVg4FruI72FaMhTMarLqwLiYuACNcBGAsYHQ/s120/umaru.png",
		colorBg: "#ee8c44"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-mh3l0YzysJA/YRkZNz6np5I/AAAAAAAAwXI/5_LO9atLRcghzYIhlgy2M4VNLQkEb3vdgCNcBGAsYHQ/s120/saitama.png",
		colorBg: "#e5b646"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZjrAsUTlXC0/YRka57MWz9I/AAAAAAAAwXY/-FqqIpJSl3wSmXU_r10wvYPGx-IPIXeBwCNcBGAsYHQ/s120/tatumaki.png",
		colorBg: "#1a562f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-0G8C-3jV7OA/YRkaIbWPk6I/AAAAAAAAwXQ/r7yNvt9hkn4iU0HQPhwesVULOvun_zV5gCNcBGAsYHQ/s120/fubuki.png",
		colorBg: "#44756a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-lmhjUoye2F4/YRkc5pWLuFI/AAAAAAAAwXg/SlINgvp3Fyk3NIbw_tHYpwR9FibI0Qd4gCNcBGAsYHQ/s120/tanmoshi.png",
		colorBg: "#5f88b8"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-5Ig6hvtKe78/YRkYYc6aazI/AAAAAAAAwXA/FnfIxmakY0gDaj2ZQNKagJB3FcOv9k1wwCNcBGAsYHQ/s120/yuzaki-masa.png",
		colorBg: "#72b1a9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--fQyJVG_a8w/YQjvnVLWzVI/AAAAAAAAv0o/h0zvBsl8ui8BslbvieRhT_S-tF9pgQ8ugCNcBGAsYHQ/s120/zero-two.png",
		colorBg: "#d89194"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-UurSmwFQu3w/YRkDhF5a50I/AAAAAAAAwWo/GE3qZZ31Sv82R8dRYLMy3dEwnKfTeqHSQCNcBGAsYHQ/s120/ichigo.png",
		colorBg: "#76b1db"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-BhMRkGfKEcQ/YRkCyrujOOI/AAAAAAAAwWg/nYTTrmR57wUZKr6ekHmd_h6g4G46F7wygCNcBGAsYHQ/s120/yosano-akiko.png",
		colorBg: "#7b8ed4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-qrSN7NyHQpQ/YRkCVDzuf5I/AAAAAAAAwWY/rACWWd0jBXUCF4ged36vtY5cnpk0c_WXwCNcBGAsYHQ/s120/sakura-nanamine.png",
		colorBg: "#9fb764"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-De8cXmbTJ5I/YRkBvmtVItI/AAAAAAAAwWQ/_1yGmv0iao8BN7VmqF7x7ljaI13P5gPEwCNcBGAsYHQ/s120/violet.png",
		colorBg: "#71a7d4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-OPUv8BBx4Rk/YRkBGf-JVoI/AAAAAAAAwWI/5y6IsQSeE5gNx5WF4Y3-W_a2C7khMZ98wCNcBGAsYHQ/s120/tamako.png",
		colorBg: "#71a7d4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-jM6COnizSUQ/YRkARvWMdjI/AAAAAAAAwWA/udx-Gdg32Y8bEENZIV3q5CI5nOqCstFrQCNcBGAsYHQ/s120/albedo.png",
		colorBg: "#5d598f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Pkj0LEwj3sQ/YRj9OC_B_XI/AAAAAAAAwVg/avaHbvdGwPE5ZNrR9jMPbhnPoRtO_XsPQCNcBGAsYHQ/s120/izumi-sagiri.png",
		colorBg: "#4eadd0"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-fTYk9A3OTZA/YSOVIMv5JEI/AAAAAAAAwl8/UqhUayokibcjXGOAakuQ7rlnWzKmylVJQCNcBGAsYHQ/s120/doraemon.png",
		colorBg: "#58d3e9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-REeSAUh2TG4/YRjg_r4LpNI/AAAAAAAAwU4/PeXKDChyqUkpBxCRK9W_0ftwKJJWzEiFwCNcBGAsYHQ/s120/nobita.png",
		colorBg: "#e6b030"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-dN7wT3ELv9g/YRjgVJIzC0I/AAAAAAAAwUw/S2aOBPSbnL4RC19tNjZoAJteha-89OA0QCNcBGAsYHQ/s120/shizuka.png",
		colorBg: "#6d97d1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-HRuLU6P55yg/YRjb4ixaiYI/AAAAAAAAwUg/niouzSPLEHsUDOJkdohnQHLadyu3qTJWwCNcBGAsYHQ/s120/mai.png",
		colorBg: "#5872a3"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-zFrWvfdTVWA/YRd8gy6n7JI/AAAAAAAAwRQ/O7sSfUZqcMoV9PmDfFD8go6Qba-V9qH4wCNcBGAsYHQ/s120/hiroomi.png",
		colorBg: "#8ca5d6"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-55_tSYQL9ug/YRZwQ40H7II/AAAAAAAAwQo/0nkUsGCA0-Y__6xParO7rnOxVW3FrBYXgCNcBGAsYHQ/s120/kenma.png",
		colorBg: "#6ebed2"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-qVfZv8mCO50/YRZvx7LPx1I/AAAAAAAAwQg/tyLE5yDN1AMIBTLRKO0Gix1quHMSnbzeACNcBGAsYHQ/s120/siesta.png",
		colorBg: "#70a8e1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZwfhIt4pnWY/YRZvL_jaulI/AAAAAAAAwQY/7p74mz07p7Almsl1sS-081MBkQDM-qjSgCNcBGAsYHQ/s120/anos.png",
		colorBg: "#57668b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6X67CRLT9xw/YRZsNC8j95I/AAAAAAAAwQI/ZoohCuuycbcHkSldFo99CDWhrgS8vDOcQCNcBGAsYHQ/s120/gin.png",
		colorBg: "#999"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-SRk-hyfU4Ps/YRZujEn7zdI/AAAAAAAAwQQ/Rhd03JAq2HE0tLs4IGxgfj6dkpVonKFOgCNcBGAsYHQ/s120/takegawa-hotaru.png",
		colorBg: "#82d8f0"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-QSjGuLAEmio/YRZrUNcSrmI/AAAAAAAAwQA/NjqD8DSbdOgefgMJlyTo33DJJvJ9_p2NQCNcBGAsYHQ/s120/shin.png",
		colorBg: "#de4646"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-RJRii2KuuHY/YRZquoSW9eI/AAAAAAAAwP4/DflBu4AwIaYTGNpOmfd8Y5-lyfKNwqPjACNcBGAsYHQ/s120/usagi-tsukino.png",
		colorBg: "#6fb6e8"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-m6oGs62c_6c/YRYuSq0_WGI/AAAAAAAAwOo/Bk8w2jJaF8I6AcDFdBM9SmUvHSamKW6-QCNcBGAsYHQ/s120/cherry.png",
		colorBg: "#c48091"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-fmUtM-zQM9o/YRYgO6j-0mI/AAAAAAAAwOI/Bh8niC5NzB4Jkjyk946vCQCXo3cI2l-1wCNcBGAsYHQ/s120/asta.png",
		colorBg: "#413b3b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-y47UaqW6fK8/YSyqP2EbkTI/AAAAAAAAw1M/fGu_F1QR2fsQyuuLt2aMY5KYBJZn5G6vACNcBGAsYHQ/s120/luck-voltia.png",
		colorBg: "#5997a5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xb561qOPUcI/YRYevHx7j-I/AAAAAAAAwN4/Y-z3NiL5rxgQA6FhdZ9JrJf0jkkfZfhCQCNcBGAsYHQ/s120/midoriya.png",
		colorBg: "#3b867a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6mzxE4TIB84/YR8nGhqvrfI/AAAAAAAAwek/gJuIglJDvUkodcGo0KMRYgXZRXJHY74jwCNcBGAsYHQ/s120/toga-himiko.png",
		colorBg: "#cf7048"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-eMi-Ag6cIXY/YRTYOJOmtmI/AAAAAAAAwLQ/kLGFd3REUiUZ2uoslq5hu4HVLPjj73GBwCNcBGAsYHQ/s120/hair-black.png",
		colorBg: "#8cbcc7"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xA6jdId--1E/YRTXcNLjY_I/AAAAAAAAwLI/38WXycddlDcVhZyLeTbYIeMJd9Cnl_Q3wCNcBGAsYHQ/s120/yumeko.png",
		colorBg: "#ba312b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-fWRP5oGItKc/YRTb6zxEwNI/AAAAAAAAwLg/4q6MkE2xvewTZDnl8XyzSJFL7AXyvLpuQCNcBGAsYHQ/s120/dimaria-yesta.png",
		colorBg: "#3f040c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-4eukR2D0IRo/YRTYYWOtD2I/AAAAAAAAwLU/6cztrMXEZrEQ-9M7esEtyAabylOSDGrbQCNcBGAsYHQ/s120/amajiki.png",
		colorBg: "#515480"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-G1IztA3Jjdk/YRTVk9_9QSI/AAAAAAAAwKw/h-qaemMIWSgMfvKPHrNw0b_65K-TiCapQCNcBGAsYHQ/s120/dazai.png",
		colorBg: "#6e7e9e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-KQK1LnPa-Bs/YSS1A2wCYkI/AAAAAAAAwoU/JuEOM_ICDXocI8AgVTV7_HRbOeKMBmnaACNcBGAsYHQ/s120/reki.png",
		colorBg: "#5a9ece"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-L7-4WTcl9cg/YRTVFzrKNkI/AAAAAAAAwKo/eWtiBmPstqk7BTWESJJNOsf3tGvv6g7RgCNcBGAsYHQ/s120/langa.png",
		colorBg: "#56789e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Eab8_mlJTa4/YRTUws8JxSI/AAAAAAAAwKg/12-f-bluNLc_d3Rs_eXLZuWtawW1yChKACNcBGAsYHQ/s120/dabi.png",
		colorBg: "#394972"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-XUThObI3ocY/YRS15lmSEVI/AAAAAAAAwKQ/cKoseU50t04u4WWs1L5A2CXt8BjyrEFKQCNcBGAsYHQ/s120/kuroko.png",
		colorBg: "#499bba"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-zTXgM6gOWLQ/YRSG1bplCCI/AAAAAAAAwI8/AqQu87U71QEyET8ZSosCv2vDVgws_z9qwCNcBGAsYHQ/s120/jinmori.png",
		colorBg: "#db432a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Iu_ufSRyN2A/YRSERnBX33I/AAAAAAAAwIs/-tITYLeOIH8xFHlftzu31YnaFKJBvMI_gCNcBGAsYHQ/s120/l-lawlie.png",
		colorBg: "#454545"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-_3PVB5nmMfU/YRTTLjnOSlI/AAAAAAAAwKY/InFTv3vobwQbbsBtvOo5cGx43ypFD54sACNcBGAsYHQ/s120/naraku.png",
		colorBg: "#9a739c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-GP8DnCIMyu4/YRSDG1i0C3I/AAAAAAAAwIk/RanzHqnT0SgYRY4N2uXm0U3gdBaivIT8QCNcBGAsYHQ/s120/sesshoumaru.png",
		colorBg: "#d93931"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-jq1aylAo5jo/YRTdk7VI1RI/AAAAAAAAwLw/d2sGi7FBggUMo3B9p8nHKfZxI9dgjiasACNcBGAsYHQ/s120/tomoe.png",
		colorBg: "#6d7094"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-GPKm4bZODgM/YRR5xF1ovKI/AAAAAAAAwIY/aDh53Q3kFksIimdSTQl-lVKcKaFLuV3sQCNcBGAsYHQ/s120/luna.png",
		colorBg: "#db98c1"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-FeUaudTnGfw/YRPh8v5oiaI/AAAAAAAAwHM/HCDEzHqRlT8kbTDtAX8QQw8XP2rGKk8FgCNcBGAsYHQ/s120/rimuru.png",
		colorBg: "#5d9bae"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-C7Z2kPSCCRU/YRR3nMkiUpI/AAAAAAAAwIE/xtcFk4AWj_IJkWTAnyO_5JHH99mHuXsDQCNcBGAsYHQ/s120/tsukishima.png",
		colorBg: "#233579"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZaAIqpupQ4o/YRSGK765q2I/AAAAAAAAwI0/GByV26sVTMsUvYvivsZMPE8dEYTSQINHQCNcBGAsYHQ/s120/hinata.png",
		colorBg: "#508cb6"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-W6Miadfk_GE/YRj_WxKAjmI/AAAAAAAAwV4/l0WseQgMeKQG62tC2Xyy264_H1MtLidfwCNcBGAsYHQ/s120/kageyama-tobio.png",
		colorBg: "#5b4e92"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-T9CkONxLm8k/YRPf5prJMFI/AAAAAAAAwG8/k_6hBBIwubEAHROMeYATMKkLaW3DKkQnwCNcBGAsYHQ/s120/tanaka.png",
		colorBg: "#da853e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-fXoRvwNdIpE/YRj-dpN1SKI/AAAAAAAAwVw/dIvo1Bcg4w8-rUbmB4qJ2ipIK2NKEWw-QCNcBGAsYHQ/s120/oikawa-tooru.png",
		colorBg: "#4a8a83"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-NnBymrk0IMQ/YROeO7_sOTI/AAAAAAAAwGc/ziDDpGoDW1ofzcwpVDHm8-3V5StfyTwBQCNcBGAsYHQ/s120/uzaki.png",
		colorBg: "#5b7eae"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-HIRiLwhw3B8/YROWkdFfBII/AAAAAAAAwGE/iqatYU8c8MQyeBKcXRrxUlsXoupTkTW0gCNcBGAsYHQ/s120/todoroki.png",
		colorBg: "#575468"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-WU-q3NhNHOE/YROWkUNba0I/AAAAAAAAwGI/J9nPwg-SmB8btzBAp4EbegtlzcJS1Jc3QCNcBGAsYHQ/s120/levi.png",
		colorBg: "#4b3b33"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xf4xB37HTJs/YQ5DtNnzArI/AAAAAAAAv9w/4SELVV2jR4crbubus_FvU1-S997LDKcQACNcBGAsYHQ/s120/eren.png",
		colorBg: "#615852"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-3prj-XMYyIU/YRjcev7aneI/AAAAAAAAwUo/TWKRGM0wCgc8lregfj24XMBJmRWeRlVGgCNcBGAsYHQ/s120/mikasa.png",
		colorBg: "#8c664e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Ibdk4YOzCyM/YSouFCpdceI/AAAAAAAAwxw/VsoWXyfX1VgcMMB8O8CYYlrk1tZlG5uoACNcBGAsYHQ/s120/hanji-zoe.png",
		colorBg: "#715f51"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-x64VmYubxkQ/YROJ3n7BzfI/AAAAAAAAwF8/NSvGfJCRg7kSs9KTHWob_X7mcZDRq7eTgCNcBGAsYHQ/s120/natsu.png",
		colorBg: "#b63232"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xEp-d8mWSbE/YRSzW79ql7I/AAAAAAAAwJw/khwKicWerJg9j8Pl-pRdo9i9ypqjRxLJQCNcBGAsYHQ/s120/lucy.png",
		colorBg: "#6a8eb5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-b4Vvz5sOGUU/YRYcGy1KHjI/AAAAAAAAwNY/YJRpR4wKhkcitKkNgujy5CP3YcoCQRFagCNcBGAsYHQ/s120/gray.png",
		colorBg: "#264b8f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Gjkw2XbPTRQ/YRS1D2ICngI/AAAAAAAAwKI/O2jyyDo9YIE7Rd946BbzMRuIdqppY8KrQCNcBGAsYHQ/s120/erza.png",
		colorBg: "#cc2c36"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-rV8kVW1MZa4/YRSyrw-q-nI/AAAAAAAAwJo/RGsTNcuBB6ckmKTObfibsITvjJplmhNtgCNcBGAsYHQ/s120/mirajane.png",
		colorBg: "#947a96"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CvaFLBWhq-Y/YSy0IvPgscI/AAAAAAAAw10/znUl_mS771MvoPx1keo3DTe-zhSb_U6DQCNcBGAsYHQ/s120/brandish.png",
		colorBg: "#93c972"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-2HCAPw0QUHY/YRTiJ0XJKiI/AAAAAAAAwMA/P7rOKf-_nV05OO78bonVxx3-R8_qMsoRACNcBGAsYHQ/s120/zeref.png",
		colorBg: "#4d709b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-yRtYb7nBr0E/YRzBU_gLV0I/AAAAAAAAwbU/X_sonF3H2lQTrlZy1BV7ilBcQpi8frlBgCNcBGAsYHQ/s120/laxus.png",
		colorBg: "#6d517e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-8jfe3JftYGw/YRYaU1AueWI/AAAAAAAAwNI/tVAV0Z5icOc80dc5zoyRMw2Axj3_EErfgCNcBGAsYHQ/s120/sting-eucliffe.png",
		colorBg: "#4d709b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-H-K_wN9MNy8/YRYbdrUgw4I/AAAAAAAAwNQ/-7tDa6sAISEJlbIz84yKQbSPJZUbbNWcgCNcBGAsYHQ/s120/wendy.png",
		colorBg: "#7183aa"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-3ysgYlyjQjo/YRYcz5E_mXI/AAAAAAAAwNg/Hfj33V6XNRE_wHnrRAkBW7o56Gjwydl4gCNcBGAsYHQ/s120/gajeel.png",
		colorBg: "#715845"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-puDGBCBEpMA/YRKx4G7KMPI/AAAAAAAAwFM/_JNx3_dZ75AOAl9Yi5AK6OBGtWV9q2hQACNcBGAsYHQ/s120/kirito.png",
		colorBg: "#5998a8"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-kdZ-a-Ba0Kw/YRKyjigWqNI/AAAAAAAAwFU/4G11nbPJ9HsmqGt2NbQ8SQiUN0esTVfJwCNcBGAsYHQ/s120/asuna.png",
		colorBg: "#be5d5d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-JGrthO2Roh8/YRJ1ubT0qFI/AAAAAAAAwE8/TXJjlZupyOAAcaNrXp-1HnBkRBwr1YCTwCNcBGAsYHQ/s120/kaori.png",
		colorBg: "#82778a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-BIrM18_ZZL0/YRKw_XC78GI/AAAAAAAAwFE/dYGr-JTSLkI2RwHgv-kOyAra7tnzAaM8gCNcBGAsYHQ/s120/gura.png",
		colorBg: "#6e93aa"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-EAkKo3u5b6g/YQ4-grJXtvI/AAAAAAAAv9I/5q99kAI5QZMcicrlhDlERmQfxdUhdBYogCNcBGAsYHQ/s120/bakugou.png",
		colorBg: "#556b71"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-2InVDhAxc8g/YQ_S1fnAICI/AAAAAAAAwBs/9EP8aMGV-WMHHSEcLsC5JcIogqmU7GuBQCNcBGAsYHQ/s120/sungjinwoo.png",
		colorBg: "#294c6d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-8OSlLqsVzDo/YQ_TcS5mWGI/AAAAAAAAwB0/U9dpJYl4H0ki37lxPDIwgsYVVUWfHvNAgCNcBGAsYHQ/s120/tsubasa.png",
		colorBg: "#329dcf"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-thPxayhCJgk/YRd7iUzQ4fI/AAAAAAAAwRI/BmtK0Oskar06sr2e2ML3PPAve8XIHSvjACNcBGAsYHQ/s120/wakabayashi.png",
		colorBg: "#ec5353"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6VvfjcG1Qko/YSo1biJSi_I/AAAAAAAAwyo/zvPXO7HpiCYSb9togzX3jbgRNwrZa6LNQCNcBGAsYHQ/s120/misaki-taro.png",
		colorBg: "#356fab"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--O_jkT24LQc/YREX0A8kAZI/AAAAAAAAwEE/8X8hJ2z6Z5A3n2-b2D_oOCkBKo_TWj4zgCNcBGAsYHQ/s120/oreki.png",
		colorBg: "#2b587e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-UckB2jBckBc/YRkEzD9LLJI/AAAAAAAAwW4/rxNah_hYNLAEwe3RhVH0m3BOQJP70i_KgCNcBGAsYHQ/s120/chitanda-eru.png",
		colorBg: "#80729a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-jb5ctGDinwo/YREd5q25CMI/AAAAAAAAwEM/q-FFPwT5r40aFjuSf-L_AZYU3BA-CJlCgCNcBGAsYHQ/s120/chaheain.png",
		colorBg: "#581f27"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-BmO6CxcuilM/YQ48dJgF4yI/AAAAAAAAv84/L_uHCWjHRsInbfjc4DTB5fSf_YcE61h7wCNcBGAsYHQ/s120/dio.png",
		colorBg: "#0d692b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--rjVyHJG820/YQ49CZSy5tI/AAAAAAAAv9A/TS5JHmGuJ8Qg7dIR61Cz0WF34vwDAtMhgCNcBGAsYHQ/s120/jotaro.png",
		colorBg: "#53544c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-U2BDkAqUc_0/YR8uZ96xjFI/AAAAAAAAwgE/SFkpUXX9TKw9AxIn00OnS3WbttE20V-lACNcBGAsYHQ/s120/giorno-giovanna.png",
		colorBg: "#b073a7"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-GUfoqwtCUMM/YQutcKmSA4I/AAAAAAAAv5g/yCR267Bt5aoJTLZ2XmapgPRKcfcGR2MUQCNcBGAsYHQ/s120/kanna.png",
		colorBg: "#c57f8c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-TkK1lZHat10/YQutoQC_JLI/AAAAAAAAv5k/Eejn12Mxgl0XnZIDAD4yZF00tiPneJOzwCNcBGAsYHQ/s120/loli.png",
		colorBg: "#3aa3c5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-rU5kOWEtTMc/YQzvR0DHARI/AAAAAAAAv7U/kTMGmdciDoEWji2CvCc7XPNnli7TcZPLgCNcBGAsYHQ/s120/satoru-gojo.png",
		colorBg: "#5e4c7c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-hZz72N2WAUA/YQuqjFY78dI/AAAAAAAAv5E/e8Yqg6WF3Bkx4YJKqImoFVHAXuFIkvcnQCNcBGAsYHQ/s120/ran.png",
		colorBg: "#8770b9"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-72_sWVkpfXg/YQuqjPD3tXI/AAAAAAAAv5A/dAiMGo-9vrsMGlQzS4SAXxt2BWmi3G8NwCNcBGAsYHQ/s120/shinichi.png",
		colorBg: "#55b5ff"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-q9iYSou-gtY/YQurPYNR9BI/AAAAAAAAv5Q/FCP21rj34-gQJlTgTCoDPwSJo7jAJX4-QCNcBGAsYHQ/s120/kaito-kid.png",
		colorBg: "#292c35"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Nn9cqk74CRI/YQqaQFBMe9I/AAAAAAAAv3M/7Ln3AFlxpw82coa1WJMo1ASoDQ1kozkXACNcBGAsYHQ/s120/luffy.png",
		colorBg: "#f1bc1c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--yQEa2GmvJ8/YQqfp2Q3e1I/AAAAAAAAv3g/LZ5odF86OMoYBrwB1pwld3msat5vY54-gCNcBGAsYHQ/s120/zoro.png",
		colorBg: "#2e483e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-d3EXXNjZcKs/YQts2JJ_CrI/AAAAAAAAv4c/OCC6qFeY_uM9oXUWEtz7YCuUzv5hudavACNcBGAsYHQ/s120/sanji.png",
		colorBg: "#484538"
	}, {
		imgAnime: "https://1.bp.blogspot.com/--qyypSJcnNo/YROJGoz7PHI/AAAAAAAAwF0/3CmiNSwzUicxszMYcp0NI2xiYA7BheEEwCNcBGAsYHQ/s120/ace.png",
		colorBg: "#b63232"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-t3MVKT5yzfw/YRKzXAmxxjI/AAAAAAAAwFc/41B5EHD0_lIxy__IKFDykcWDBqar0nwDgCNcBGAsYHQ/s120/nico.png",
		colorBg: "#555b8f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-F7vYcascEwM/YR8t4rl992I/AAAAAAAAwf8/Moa1llXYzasPDE8tCVefKAMFoEXZgqbsQCNcBGAsYHQ/s120/doflamingo.png",
		colorBg: "#d1819f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-pnkm5m1xDJ8/YRPyW6j6VsI/AAAAAAAAwH0/wNMrb4XXVYk8KVmFCBgSe_DHcSYa3HAyQCNcBGAsYHQ/s120/nami.png",
		colorBg: "#34a6b4"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Fa4JXpOY0V8/YQ5FIa8XYGI/AAAAAAAAv94/buzlwK_chWc1BwHshCW50ijsu6juwm7ygCNcBGAsYHQ/s120/shanks.png",
		colorBg: "#474e6a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-cV_zpPy9daA/YRYhz-ntOII/AAAAAAAAwOY/7tSf4VK9DvITyqxUuhfnxr1kgrebCCubQCNcBGAsYHQ/s120/trafalgar-law.png",
		colorBg: "#efb23e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-L6zjbaWc0VM/YQqZ_877g4I/AAAAAAAAv3E/k4V_f1JiP-gmKq0Hj5IItqIbjHD5mULtgCNcBGAsYHQ/s120/naruto.png",
		colorBg: "#ec7230"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-5YSrPZS5OTQ/YQtt31nppUI/AAAAAAAAv4k/aWWMO75j2EALPqCHfLKzyFcXB6qhbP4zgCNcBGAsYHQ/s120/sasuke.png",
		colorBg: "#103555"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-xhj9vr_icEw/YQkNus86DjI/AAAAAAAAv1Y/T_FYJlBMT1A6AxsPEDiAfMnDbdc8nDb2gCNcBGAsYHQ/s120/kakashi.png",
		colorBg: "#626b57"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Ar1qfZgfJDM/YRSz5fI_DyI/AAAAAAAAwJ4/a103ZpEJoIUhATEfMwsQDaMdAFD53MCpgCNcBGAsYHQ/s120/sakura.png",
		colorBg: "#cc7a7f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CS2v0BvqwBE/YRS0bnCbVzI/AAAAAAAAwKA/rXLqcIbI9pEmR7pnH-VoXGNVstDhEJ_AgCNcBGAsYHQ/s120/tusnade.png",
		colorBg: "#4c7c60"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-7LF01HmPHPw/YQ4JkrsdbdI/AAAAAAAAv8Q/0Qi_816Sa7UUEyKgRjXLBIoKG-LOamhTQCNcBGAsYHQ/s120/yahiko.png",
		colorBg: "#7d2727"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-Her8xlrrQCY/YRjYBdI8rhI/AAAAAAAAwTo/zRslu89q2TQgMRRPxWAc0z7lT_KJYpNuACNcBGAsYHQ/s120/nagato.png",
		colorBg: "#981d18"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-n_CBrOs73kU/YRjYbRF1xQI/AAAAAAAAwTw/9di9txxBBvAgYgbsQVlVMcpA8f4zkNBewCNcBGAsYHQ/s120/konan.png",
		colorBg: "#981d18"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CKcBITDyc58/YQ4KtF_AtlI/AAAAAAAAv8Y/KJwF5uAC1mwnOD7xdKqL41yP-NJguA9AQCNcBGAsYHQ/s120/obito.png",
		colorBg: "#1c4d68"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-KcCCrfrbxEw/YRjY9WpdJtI/AAAAAAAAwT4/GdEcIJAcuvAkaNbj7M_xX0Nn1eFP1JHPQCNcBGAsYHQ/s120/kakuzu.png",
		colorBg: "#777"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-B3-VALnkvQg/YRjZa-inEQI/AAAAAAAAwUA/OFDsr0PgqRYnbVTpgVzHfrdFsIYV-SQyQCNcBGAsYHQ/s120/deidara.png",
		colorBg: "#c7a548"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-CWo5dbAuE4M/YQ_SFnxgO0I/AAAAAAAAwBY/keSGguTH4kM7j1x20von_KoLXUfuMUzUACNcBGAsYHQ/s120/itachi.png",
		colorBg: "#47282b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-fg756cApCdU/YRd5sMNvQHI/AAAAAAAAwQ4/3YqvC_exELkz_KE5hmJrvyk9tYz8wwvdgCNcBGAsYHQ/s120/hidan.png",
		colorBg: "#b95e57"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-G0-V1YZ1bn0/YRd6ZEodxuI/AAAAAAAAwRA/HWGpEL3BUEgJLXd4jR4Ri7k4oDL_Vt-5ACNcBGAsYHQ/s120/kisame.png",
		colorBg: "#b95e57"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-keYdneZwxjE/YRjZ72jvVfI/AAAAAAAAwUI/0TqPvxHAnhEbLruw0uCKxy_G2h1kZM0-QCNcBGAsYHQ/s120/sasori.png",
		colorBg: "#b8525b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-hQDC3aa-qK8/YRjabB3E3VI/AAAAAAAAwUQ/3shQaBOJiBUVqQmVTV5Z-WjxuKxZDbAWgCNcBGAsYHQ/s120/zetsu.png",
		colorBg: "#6f8461"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-iIJz2RT-k7I/YRja0oJ9b5I/AAAAAAAAwUY/3neGuO_H_uo9__RRPgLZR6i0h3S1SvfigCNcBGAsYHQ/s120/orochimaru.png",
		colorBg: "#705c4e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-1rP0v0irX9g/YQ_STpG4JgI/AAAAAAAAwBg/cGz_s3ujvGcSIjd9KgFhRkQhlhA3TqfDwCNcBGAsYHQ/s120/tenten.png",
		colorBg: "#47282b"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ofuo8FrbTyQ/YQ4_TmpZ5FI/AAAAAAAAv9Q/9s6GofFQGnwgXkkheU-ze-XRXztmAcM7ACNcBGAsYHQ/s120/kushina.png",
		colorBg: "#9c3c4c"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-i9e4qs57BiA/YQ5BlPo1gXI/AAAAAAAAv9c/hUbDm1fVJokZzcnd3fXFAl8LVIQHYcCjwCNcBGAsYHQ/s120/minato.png",
		colorBg: "#777"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-USIUbP_2vZg/YRYdjH_WWFI/AAAAAAAAwNo/5WPZALM6aewZsoWdT4uSYPzgP9M-_NEOgCNcBGAsYHQ/s120/gaara.png",
		colorBg: "#85464d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-1m-EbLHrcaE/YRYeMmFZT9I/AAAAAAAAwNw/wcqubpGEAr0w-XRmabX1UAEbPOswViJ9QCNcBGAsYHQ/s120/hashirama.png",
		colorBg: "#777"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-tZgdLoNT5dc/YRYw78qm5II/AAAAAAAAwOw/V5jmGUQhZ6sSmN6aODnBSv-oubn2O88EACNcBGAsYHQ/s120/madara.png",
		colorBg: "#a3645d"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-6f-A5erlKJ4/YRYxXHvDk2I/AAAAAAAAwO4/XiSfCDQB-CYorAv4DZK8cZUpFH4CCPw9wCNcBGAsYHQ/s120/shikamaru.png",
		colorBg: "#6f7f5e"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-lmCYjuEEqT4/YRYyAJxY5pI/AAAAAAAAwPE/C04ktU6o9QIQHpwRC4IXUGlXVJgsMspsQCNcBGAsYHQ/s120/temari.png",
		colorBg: "#a095b5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-hQS6uQuxWTo/YRj8PN8QL7I/AAAAAAAAwVY/rFO88neKNQA4uzGHPZ1eKDcB3_ldZXk3gCNcBGAsYHQ/s120/uchiha-shisui.png",
		colorBg: "#595f41"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-RWk_79P5Hu4/YRj9uoKnPbI/AAAAAAAAwVo/zqNQfLLGwtMw_KlHjwnSAvrmL1J59XLvQCNcBGAsYHQ/s120/hinata-hyuga.png",
		colorBg: "#816e87"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-_tcUKKOmidw/YRkEYP1xAvI/AAAAAAAAwWw/W8WO76prD4QIZuytIxQQrRvkEr8TYy7VgCNcBGAsYHQ/s120/asuma.png",
		colorBg: "#74795a"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-ZUzK61zRQyw/YRooknSYFTI/AAAAAAAAwY0/xig7pXLJZG4D1ZUc8uipYrcYPXocvF18ACNcBGAsYHQ/s120/tobirama.png",
		colorBg: "#3d6499"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-_uJ-8W6TcNA/YQ5JiTVjC2I/AAAAAAAAv-Q/ng_PK2jqAxUzV3AaT6xvJEYmaHuYRsmUwCNcBGAsYHQ/s120/songoku.png",
		colorBg: "#f69e3f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-DHKmKVOWB5E/YQ5KOhqCUAI/AAAAAAAAv-Y/UpV2SArQMQwTy1lB6loC83m9vzjsIB0rwCNcBGAsYHQ/s120/vegeta.png",
		colorBg: "#223f89"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-mx4yeGDk1cM/YQ5KtIpbJJI/AAAAAAAAv-g/wbWhxO56coIJeWejlmSttEJOaB-4IqFUgCNcBGAsYHQ/s120/gohan.png",
		colorBg: "#326ee3"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-rMrX5g2G9LI/YQ5MpVpVtaI/AAAAAAAAv-o/M4DDulBEPl8O0GPc4OQs8nVw2cQ06MuvgCNcBGAsYHQ/s120/black-goku.png",
		colorBg: "#2c2b2f"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-UQDKkhQBO1g/YQj2sRzBrRI/AAAAAAAAv04/tEpL58TzhB4gMJLp0GmebOs9o-Wq76wcgCNcBGAsYHQ/s120/taki.png",
		colorBg: "#539bc5"
	}, {
		imgAnime: "https://1.bp.blogspot.com/-SHa2sh1AzeY/YQj3OVQhWHI/AAAAAAAAv1A/CfDtQBtC8vUq20DMHKzhSyRk5u2ycuwfwCNcBGAsYHQ/s120/mitsuha.png",
		colorBg: "#8f7fa4"
	}
];